set_property SRC_FILE_INFO {cfile:d:/pcie_eth_10g/ram_eth/ram_eth.srcs/sources_1/ip/ClkGen/ClkGen.xdc rfile:../ram_eth.srcs/sources_1/ip/ClkGen/ClkGen.xdc id:1 order:EARLY scoped_inst:eth_test/u1/ten_gig_eth_example_top/inst_ClkGen/inst} [current_design]
set_property SRC_FILE_INFO {cfile:d:/pcie_eth_10g/ram_eth/ram_eth.srcs/sources_1/ip/ClkGen/ClkGen.xdc rfile:../ram_eth.srcs/sources_1/ip/ClkGen/ClkGen.xdc id:2 order:EARLY scoped_inst:eth_test/u2/ten_gig_eth_example_top/inst_ClkGen/inst} [current_design]
set_property SRC_FILE_INFO {cfile:d:/pcie_eth_10g/ram_eth/ram_eth.srcs/sources_1/ip/ten_gig_eth_pcs_pma_0/ip_0/synth/ten_gig_eth_pcs_pma_0_gt.xdc rfile:../ram_eth.srcs/sources_1/ip/ten_gig_eth_pcs_pma_0/ip_0/synth/ten_gig_eth_pcs_pma_0_gt.xdc id:3 order:EARLY scoped_inst:eth_test/u1/ten_gig_eth_example_top/inst_ten_gig_mac_wrapper/ten_gig_eth_pcs_pma_i/inst/ten_gig_eth_pcs_pma_0_gt_i/inst} [current_design]
set_property SRC_FILE_INFO {cfile:d:/pcie_eth_10g/ram_eth/ram_eth.srcs/sources_1/ip/ten_gig_eth_pcs_pma_0/ip_0/synth/ten_gig_eth_pcs_pma_0_gt.xdc rfile:../ram_eth.srcs/sources_1/ip/ten_gig_eth_pcs_pma_0/ip_0/synth/ten_gig_eth_pcs_pma_0_gt.xdc id:4 order:EARLY scoped_inst:eth_test/u2/ten_gig_eth_example_top/inst_ten_gig_mac_wrapper/ten_gig_eth_pcs_pma_i/inst/ten_gig_eth_pcs_pma_0_gt_i/inst} [current_design]
set_property SRC_FILE_INFO {cfile:d:/pcie_eth_10g/ram_eth/ram_eth.srcs/sources_1/ip/ten_gig_eth_pcs_pma_0/synth/ten_gig_eth_pcs_pma_0.xdc rfile:../ram_eth.srcs/sources_1/ip/ten_gig_eth_pcs_pma_0/synth/ten_gig_eth_pcs_pma_0.xdc id:5 order:EARLY scoped_inst:eth_test/u1/ten_gig_eth_example_top/inst_ten_gig_mac_wrapper/ten_gig_eth_pcs_pma_i/inst} [current_design]
set_property SRC_FILE_INFO {cfile:d:/pcie_eth_10g/ram_eth/ram_eth.srcs/sources_1/ip/ten_gig_eth_pcs_pma_0/synth/ten_gig_eth_pcs_pma_0.xdc rfile:../ram_eth.srcs/sources_1/ip/ten_gig_eth_pcs_pma_0/synth/ten_gig_eth_pcs_pma_0.xdc id:6 order:EARLY scoped_inst:eth_test/u2/ten_gig_eth_example_top/inst_ten_gig_mac_wrapper/ten_gig_eth_pcs_pma_i/inst} [current_design]
set_property SRC_FILE_INFO {cfile:d:/pcie_eth_10g/ram_eth/ram_eth.srcs/sources_1/ip/ten_gig_eth_mac_0/synth/ten_gig_eth_mac_0.xdc rfile:../ram_eth.srcs/sources_1/ip/ten_gig_eth_mac_0/synth/ten_gig_eth_mac_0.xdc id:7 order:EARLY scoped_inst:eth_test/u1/ten_gig_eth_example_top/inst_ten_gig_mac_wrapper/fifo_block_i/xgmac_support_i/xgmac_i/inst} [current_design]
set_property SRC_FILE_INFO {cfile:d:/pcie_eth_10g/ram_eth/ram_eth.srcs/sources_1/ip/ten_gig_eth_mac_0/synth/ten_gig_eth_mac_0.xdc rfile:../ram_eth.srcs/sources_1/ip/ten_gig_eth_mac_0/synth/ten_gig_eth_mac_0.xdc id:8 order:EARLY scoped_inst:eth_test/u2/ten_gig_eth_example_top/inst_ten_gig_mac_wrapper/fifo_block_i/xgmac_support_i/xgmac_i/inst} [current_design]
set_property SRC_FILE_INFO {cfile:D:/pcie_eth_10g/ram_eth/ram_eth.srcs/constrs_1/imports/vivado/PCIE_to_ram_ing/FPGA/pcieax7103x4_128ddr3/PCIe.srcs/constrs_1/new/PCIe.xdc rfile:../ram_eth.srcs/constrs_1/imports/vivado/PCIE_to_ram_ing/FPGA/pcieax7103x4_128ddr3/PCIe.srcs/constrs_1/new/PCIe.xdc id:9} [current_design]
set_property SRC_FILE_INFO {cfile:d:/pcie_eth_10g/ram_eth/ram_eth.srcs/sources_1/ip/ten_gig_eth_pcs_pma_0/synth/ten_gig_eth_pcs_pma_0_clocks.xdc rfile:../ram_eth.srcs/sources_1/ip/ten_gig_eth_pcs_pma_0/synth/ten_gig_eth_pcs_pma_0_clocks.xdc id:10 order:LATE scoped_inst:eth_test/u1/ten_gig_eth_example_top/inst_ten_gig_mac_wrapper/ten_gig_eth_pcs_pma_i/inst} [current_design]
set_property SRC_FILE_INFO {cfile:d:/pcie_eth_10g/ram_eth/ram_eth.srcs/sources_1/ip/ten_gig_eth_pcs_pma_0/synth/ten_gig_eth_pcs_pma_0_clocks.xdc rfile:../ram_eth.srcs/sources_1/ip/ten_gig_eth_pcs_pma_0/synth/ten_gig_eth_pcs_pma_0_clocks.xdc id:11 order:LATE scoped_inst:eth_test/u2/ten_gig_eth_example_top/inst_ten_gig_mac_wrapper/ten_gig_eth_pcs_pma_i/inst} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1_p]] 0.033330000000000005
set_property src_info {type:SCOPED_XDC file:2 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1_p]] 0.033330000000000005
set_property src_info {type:SCOPED_XDC file:3 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE3_CHANNEL_X0Y0 [get_cells -hierarchical -filter {NAME =~ *gen_channel_container[0].*gen_gthe3_channel_inst[0].GTHE3_CHANNEL_PRIM_INST}]
set_property src_info {type:SCOPED_XDC file:4 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE3_CHANNEL_X0Y0 [get_cells -hierarchical -filter {NAME =~ *gen_channel_container[0].*gen_gthe3_channel_inst[0].GTHE3_CHANNEL_PRIM_INST}]
set_property src_info {type:SCOPED_XDC file:5 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells -hierarchical -filter {NAME =~ *elastic*rd_truegray_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -to [get_cells -hierarchical -filter {NAME =~ *elastic*rag_writesync0_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -datapath_only 6.400
set_property src_info {type:SCOPED_XDC file:5 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells -hierarchical -filter {NAME =~ *elastic*wr_gray_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -to [get_cells -hierarchical -filter {NAME =~ *elastic*wr_gray_rdclk0_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -datapath_only 3.100
set_property src_info {type:SCOPED_XDC file:5 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells -hierarchical -filter {NAME =~ *elastic*rd_lastgray_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -to [get_cells -hierarchical -filter {NAME =~ *elastic*rd_lastgray_wrclk0_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -datapath_only 6.400
set_property src_info {type:SCOPED_XDC file:5 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells -of [all_fanin -flat [get_pins -of_objects [get_cells -hierarchical -filter {NAME =~ *resyncs*d1_reg}] -filter {NAME =~ *D}]] -filter {IS_SEQUENTIAL=="1" && NAME !~ "*resyncs*d1_reg"}] -to [get_pins -of_objects [get_cells -hierarchical -filter {NAME =~ *resyncs*d1_reg}] -filter {NAME =~ *D}] 3.100 -datapath_only
set_property src_info {type:SCOPED_XDC file:5 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hierarchical -filter {NAME =~ *drp_ipif_i*synch_*d_reg_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -to [get_pins -of_objects [get_cells -hierarchical -filter {NAME =~ *drp_ipif_i*synch_*q_reg*}] -filter {NAME =~ *D || NAME =~ *R || NAME =~ *S}] 3.100
set_property src_info {type:SCOPED_XDC file:6 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells -hierarchical -filter {NAME =~ *elastic*rd_truegray_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -to [get_cells -hierarchical -filter {NAME =~ *elastic*rag_writesync0_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -datapath_only 6.400
set_property src_info {type:SCOPED_XDC file:6 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells -hierarchical -filter {NAME =~ *elastic*wr_gray_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -to [get_cells -hierarchical -filter {NAME =~ *elastic*wr_gray_rdclk0_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -datapath_only 3.100
set_property src_info {type:SCOPED_XDC file:6 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells -hierarchical -filter {NAME =~ *elastic*rd_lastgray_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -to [get_cells -hierarchical -filter {NAME =~ *elastic*rd_lastgray_wrclk0_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -datapath_only 6.400
set_property src_info {type:SCOPED_XDC file:6 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells -of [all_fanin -flat [get_pins -of_objects [get_cells -hierarchical -filter {NAME =~ *resyncs*d1_reg}] -filter {NAME =~ *D}]] -filter {IS_SEQUENTIAL=="1" && NAME !~ "*resyncs*d1_reg"}] -to [get_pins -of_objects [get_cells -hierarchical -filter {NAME =~ *resyncs*d1_reg}] -filter {NAME =~ *D}] 3.100 -datapath_only
set_property src_info {type:SCOPED_XDC file:6 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hierarchical -filter {NAME =~ *drp_ipif_i*synch_*d_reg_reg* && (PRIMITIVE_SUBGROUP =~ flop || PRIMITIVE_SUBGROUP =~ SDR)}] -to [get_pins -of_objects [get_cells -hierarchical -filter {NAME =~ *drp_ipif_i*synch_*q_reg*}] -filter {NAME =~ *D || NAME =~ *R || NAME =~ *S}] 3.100
set_property src_info {type:SCOPED_XDC file:7 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells ten_gig_eth_mac_0_core/rx/rx_pause_control/pause_quanta_reg[*]] -to [get_cells ten_gig_eth_mac_0_core/tx/tx_cntl/pause_tx_quanta_reg[*]]
set_property src_info {type:SCOPED_XDC file:8 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 6.4000 -datapath_only -from [get_cells ten_gig_eth_mac_0_core/rx/rx_pause_control/pause_quanta_reg[*]] -to [get_cells ten_gig_eth_mac_0_core/tx/tx_cntl/pause_tx_quanta_reg[*]]
set_property src_info {type:XDC file:9 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E13 [get_ports key]
set_property src_info {type:XDC file:9 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports key]
set_property src_info {type:XDC file:9 line:13 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 8.000 [get_ports rgmii1_rxc]
set_property src_info {type:XDC file:9 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii1_rxd[*]}]
set_property src_info {type:XDC file:9 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii1_txd[*]}]
set_property src_info {type:XDC file:9 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {rgmii1_txd[*]}]
set_property src_info {type:XDC file:9 line:18 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name sys_clk [get_ports sys_clk_clk_p]
set_property src_info {type:XDC file:9 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F10 [get_ports {sys_clk_clk_p[0]}]
set_property src_info {type:XDC file:9 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15 [get_ports sys_ddr_clk_p]
set_property src_info {type:XDC file:9 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15 [get_ports sys_ddr_clk_n]
set_property src_info {type:XDC file:9 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T4 [get_ports sys_ddr_clk_n]
set_property src_info {type:XDC file:9 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R4 [get_ports sys_ddr_clk_p]
set_property src_info {type:XDC file:9 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS15 [get_ports sys_rst]
set_property src_info {type:XDC file:9 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports e1_mdc]
set_property src_info {type:XDC file:9 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports e1_mdio]
set_property src_info {type:XDC file:9 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports e1_reset]
set_property src_info {type:XDC file:9 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii1_rxc]
set_property src_info {type:XDC file:9 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii1_rxctl]
set_property src_info {type:XDC file:9 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii1_txc]
set_property src_info {type:XDC file:9 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii1_txctl]
set_property src_info {type:XDC file:9 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports rgmii1_txc]
set_property src_info {type:XDC file:9 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports rgmii1_txctl]
set_property src_info {type:XDC file:9 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C19 [get_ports {rgmii1_rxd[3]}]
set_property src_info {type:XDC file:9 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C18 [get_ports {rgmii1_rxd[2]}]
set_property src_info {type:XDC file:9 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B18 [get_ports {rgmii1_rxd[1]}]
set_property src_info {type:XDC file:9 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A16 [get_ports {rgmii1_rxd[0]}]
set_property src_info {type:XDC file:9 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A18 [get_ports {rgmii1_txd[3]}]
set_property src_info {type:XDC file:9 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A19 [get_ports {rgmii1_txd[2]}]
set_property src_info {type:XDC file:9 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D20 [get_ports {rgmii1_txd[1]}]
set_property src_info {type:XDC file:9 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C20 [get_ports {rgmii1_txd[0]}]
set_property src_info {type:XDC file:9 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B16 [get_ports e1_mdc]
set_property src_info {type:XDC file:9 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B15 [get_ports e1_mdio]
set_property src_info {type:XDC file:9 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D16 [get_ports e1_reset]
set_property src_info {type:XDC file:9 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B17 [get_ports rgmii1_rxc]
set_property src_info {type:XDC file:9 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A15 [get_ports rgmii1_rxctl]
set_property src_info {type:XDC file:9 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E18 [get_ports rgmii1_txc]
set_property src_info {type:XDC file:9 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F18 [get_ports rgmii1_txctl]
set_property src_info {type:XDC file:9 line:71 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 8.000 [get_ports rgmii2_rxc]
set_property src_info {type:XDC file:9 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii2_rxd[*]}]
set_property src_info {type:XDC file:9 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii2_txd[*]}]
set_property src_info {type:XDC file:9 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {rgmii2_txd[*]}]
set_property src_info {type:XDC file:9 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports e2_mdc]
set_property src_info {type:XDC file:9 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports e2_mdio]
set_property src_info {type:XDC file:9 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports e2_reset]
set_property src_info {type:XDC file:9 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii2_rxc]
set_property src_info {type:XDC file:9 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii2_rxctl]
set_property src_info {type:XDC file:9 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii2_txc]
set_property src_info {type:XDC file:9 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii2_txctl]
set_property src_info {type:XDC file:9 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports rgmii2_txc]
set_property src_info {type:XDC file:9 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports rgmii2_txctl]
set_property src_info {type:XDC file:9 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C17 [get_ports {rgmii2_rxd[3]}]
set_property src_info {type:XDC file:9 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D19 [get_ports {rgmii2_rxd[2]}]
set_property src_info {type:XDC file:9 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B20 [get_ports {rgmii2_rxd[1]}]
set_property src_info {type:XDC file:9 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A20 [get_ports {rgmii2_rxd[0]}]
set_property src_info {type:XDC file:9 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A13 [get_ports {rgmii2_txd[3]}]
set_property src_info {type:XDC file:9 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C15 [get_ports {rgmii2_txd[2]}]
set_property src_info {type:XDC file:9 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C14 [get_ports {rgmii2_txd[1]}]
set_property src_info {type:XDC file:9 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E17 [get_ports {rgmii2_txd[0]}]
set_property src_info {type:XDC file:9 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F20 [get_ports e2_mdc]
set_property src_info {type:XDC file:9 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C22 [get_ports e2_mdio]
set_property src_info {type:XDC file:9 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B22 [get_ports e2_reset]
set_property src_info {type:XDC file:9 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E19 [get_ports rgmii2_rxc]
set_property src_info {type:XDC file:9 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F19 [get_ports rgmii2_rxctl]
set_property src_info {type:XDC file:9 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A14 [get_ports rgmii2_txc]
set_property src_info {type:XDC file:9 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D17 [get_ports rgmii2_txctl]
set_property src_info {type:XDC file:9 line:196 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J20 [get_ports sys_rst_n]
set_property src_info {type:XDC file:9 line:239 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {wait_cnt_reg[21]}]
set_property src_info {type:XDC file:9 line:240 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {wait_cnt_reg[23]}]
set_property src_info {type:XDC file:9 line:241 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {wait_cnt_reg[24]}]
set_property src_info {type:XDC file:9 line:242 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {wait_cnt_reg[3]}]
set_property src_info {type:XDC file:9 line:243 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {wait_cnt_reg[4]}]
set_property src_info {type:XDC file:9 line:244 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {wait_cnt_reg[10]}]
set_property src_info {type:XDC file:9 line:245 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {wait_cnt_reg[22]}]
set_property src_info {type:XDC file:9 line:246 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {wait_cnt_reg[20]}]
set_property src_info {type:XDC file:9 line:248 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {wait_cnt_reg[25]}]
set_property src_info {type:XDC file:9 line:249 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {wait_cnt_reg[12]}]
set_property src_info {type:XDC file:9 line:250 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {wait_cnt_reg[5]}]
set_property src_info {type:XDC file:9 line:251 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {wait_cnt_reg[30]}]
set_property src_info {type:XDC file:9 line:252 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {wait_cnt_reg[2]}]
set_property src_info {type:XDC file:9 line:253 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {wait_cnt_reg[26]}]
set_property src_info {type:XDC file:9 line:254 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {wait_cnt_reg[15]}]
set_property src_info {type:XDC file:9 line:256 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {wait_cnt_reg[29]}]
set_property src_info {type:XDC file:9 line:257 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets eth_test/u2/gmii_rx_dv]
set_property src_info {type:XDC file:9 line:259 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {wait_cnt_reg[13]}]
set_property src_info {type:XDC file:9 line:260 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets eth_test/u1/gmii_rx_dv]
set_property src_info {type:XDC file:9 line:262 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {wait_cnt_reg[9]}]
set_property src_info {type:XDC file:9 line:263 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {wait_cnt_reg[1]}]
set_property src_info {type:XDC file:9 line:264 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {wait_cnt_reg[6]}]
set_property src_info {type:XDC file:9 line:265 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {wait_cnt_reg[11]}]
set_property src_info {type:XDC file:9 line:266 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {wait_cnt_reg[14]}]
set_property src_info {type:XDC file:9 line:267 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {wait_cnt_reg[16]}]
set_property src_info {type:XDC file:9 line:268 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {wait_cnt_reg[17]}]
set_property src_info {type:XDC file:9 line:269 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {wait_cnt_reg[31]}]
set_property src_info {type:XDC file:9 line:270 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {wait_cnt_reg[18]}]
set_property src_info {type:XDC file:9 line:271 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {wait_cnt_reg[28]}]
set_property src_info {type:XDC file:9 line:272 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {wait_cnt_reg[7]}]
set_property src_info {type:XDC file:9 line:273 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {wait_cnt_reg[8]}]
set_property src_info {type:XDC file:9 line:274 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {wait_cnt_reg[19]}]
set_property src_info {type:XDC file:9 line:275 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {wait_cnt_reg[27]}]
set_property src_info {type:XDC file:9 line:284 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {eth_test/u1/gmii_rxd[5]}]
set_property src_info {type:XDC file:9 line:285 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {eth_test/u1/gmii_rxd[7]}]
set_property src_info {type:XDC file:9 line:286 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {eth_test/u1/gmii_rxd[6]}]
set_property src_info {type:XDC file:9 line:287 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {eth_test/u1/gmii_rxd[0]}]
set_property src_info {type:XDC file:9 line:288 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {eth_test/u1/gmii_rxd[1]}]
set_property src_info {type:XDC file:9 line:289 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {eth_test/u1/gmii_rxd[2]}]
set_property src_info {type:XDC file:9 line:290 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {eth_test/u1/gmii_rxd[3]}]
set_property src_info {type:XDC file:9 line:291 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {eth_test/u1/gmii_rxd[4]}]
set_property src_info {type:XDC file:9 line:293 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {eth_test/u2/gmii_rxd[0]}]
set_property src_info {type:XDC file:9 line:294 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {eth_test/u2/gmii_rxd[4]}]
set_property src_info {type:XDC file:9 line:295 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {eth_test/u2/gmii_rxd[6]}]
set_property src_info {type:XDC file:9 line:296 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {eth_test/u2/gmii_rxd[7]}]
set_property src_info {type:XDC file:9 line:297 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {eth_test/u2/gmii_rxd[3]}]
set_property src_info {type:XDC file:9 line:298 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {eth_test/u2/gmii_rxd[1]}]
set_property src_info {type:XDC file:9 line:299 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {eth_test/u2/gmii_rxd[2]}]
set_property src_info {type:XDC file:9 line:300 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {eth_test/u2/gmii_rxd[5]}]
set_property src_info {type:XDC file:9 line:368 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_source_addr[0]}]
set_property src_info {type:XDC file:9 line:369 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_source_addr[10]}]
set_property src_info {type:XDC file:9 line:370 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_source_addr[11]}]
set_property src_info {type:XDC file:9 line:371 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_source_addr[12]}]
set_property src_info {type:XDC file:9 line:372 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_source_addr[13]}]
set_property src_info {type:XDC file:9 line:373 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_source_addr[14]}]
set_property src_info {type:XDC file:9 line:374 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_source_addr[15]}]
set_property src_info {type:XDC file:9 line:375 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_source_addr[16]}]
set_property src_info {type:XDC file:9 line:376 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_source_addr[17]}]
set_property src_info {type:XDC file:9 line:377 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_source_addr[18]}]
set_property src_info {type:XDC file:9 line:378 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_source_addr[19]}]
set_property src_info {type:XDC file:9 line:379 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_source_addr[1]}]
set_property src_info {type:XDC file:9 line:380 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_source_addr[20]}]
set_property src_info {type:XDC file:9 line:381 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_source_addr[21]}]
set_property src_info {type:XDC file:9 line:382 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_source_addr[22]}]
set_property src_info {type:XDC file:9 line:383 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_source_addr[23]}]
set_property src_info {type:XDC file:9 line:384 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_source_addr[24]}]
set_property src_info {type:XDC file:9 line:385 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_source_addr[25]}]
set_property src_info {type:XDC file:9 line:386 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_source_addr[26]}]
set_property src_info {type:XDC file:9 line:387 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_source_addr[27]}]
set_property src_info {type:XDC file:9 line:388 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_source_addr[28]}]
set_property src_info {type:XDC file:9 line:389 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_source_addr[29]}]
set_property src_info {type:XDC file:9 line:390 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_source_addr[2]}]
set_property src_info {type:XDC file:9 line:391 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_source_addr[30]}]
set_property src_info {type:XDC file:9 line:392 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_source_addr[31]}]
set_property src_info {type:XDC file:9 line:393 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_source_addr[3]}]
set_property src_info {type:XDC file:9 line:394 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_source_addr[4]}]
set_property src_info {type:XDC file:9 line:395 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_source_addr[5]}]
set_property src_info {type:XDC file:9 line:396 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_source_addr[6]}]
set_property src_info {type:XDC file:9 line:397 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_source_addr[7]}]
set_property src_info {type:XDC file:9 line:398 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_source_addr[8]}]
set_property src_info {type:XDC file:9 line:399 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_source_addr[9]}]
set_property src_info {type:XDC file:9 line:400 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets state_prepared_en]
set_property src_info {type:XDC file:9 line:401 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_test/u2/mac_test0/mac_top0/mac_rx0/udp0/udp_rx_cnt_reg[8]}]
set_property src_info {type:XDC file:9 line:402 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_test/u2/mac_test0/mac_top0/mac_rx0/udp0/udp_rx_cnt_reg[3]}]
set_property src_info {type:XDC file:9 line:403 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_test/u2/mac_test0/mac_top0/mac_rx0/udp0/udp_rx_cnt_reg[11]}]
set_property src_info {type:XDC file:9 line:404 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_test/u2/mac_test0/mac_top0/mac_rx0/udp0/udp_rx_cnt_reg[5]}]
set_property src_info {type:XDC file:9 line:405 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_test/u2/mac_test0/mac_top0/mac_rx0/udp0/udp_rx_cnt_reg[15]}]
set_property src_info {type:XDC file:9 line:406 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_test/u2/mac_test0/mac_top0/mac_rx0/udp0/udp_rx_cnt_reg[6]}]
set_property src_info {type:XDC file:9 line:407 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_test/u2/mac_test0/mac_top0/mac_rx0/udp0/udp_rx_cnt_reg[10]}]
set_property src_info {type:XDC file:9 line:408 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_test/u2/mac_test0/mac_top0/mac_rx0/udp0/udp_rx_cnt_reg[12]}]
set_property src_info {type:XDC file:9 line:409 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_test/u2/mac_test0/mac_top0/mac_rx0/udp0/udp_rx_cnt_reg[1]}]
set_property src_info {type:XDC file:9 line:410 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_test/u2/mac_test0/mac_top0/mac_rx0/udp0/udp_rx_cnt_reg[2]}]
set_property src_info {type:XDC file:9 line:411 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_test/u2/mac_test0/mac_top0/mac_rx0/udp0/udp_rx_cnt_reg[9]}]
set_property src_info {type:XDC file:9 line:412 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_test/u2/mac_test0/mac_top0/mac_rx0/udp0/udp_rx_cnt_reg[14]}]
set_property src_info {type:XDC file:9 line:413 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_test/u2/mac_test0/mac_top0/mac_rx0/udp0/udp_rx_cnt_reg[0]}]
set_property src_info {type:XDC file:9 line:414 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_test/u2/mac_test0/mac_top0/mac_rx0/udp0/udp_rx_cnt_reg[4]}]
set_property src_info {type:XDC file:9 line:415 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_test/u2/mac_test0/mac_top0/mac_rx0/udp0/udp_rx_cnt_reg[7]}]
set_property src_info {type:XDC file:9 line:416 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_test/u2/mac_test0/mac_top0/mac_rx0/udp0/udp_rx_cnt_reg[13]}]
set_property src_info {type:XDC file:9 line:418 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_destination_addr[0]}]
set_property src_info {type:XDC file:9 line:419 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_destination_addr[10]}]
set_property src_info {type:XDC file:9 line:420 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_destination_addr[11]}]
set_property src_info {type:XDC file:9 line:421 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_destination_addr[12]}]
set_property src_info {type:XDC file:9 line:422 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_destination_addr[13]}]
set_property src_info {type:XDC file:9 line:423 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_destination_addr[14]}]
set_property src_info {type:XDC file:9 line:424 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_destination_addr[15]}]
set_property src_info {type:XDC file:9 line:425 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_destination_addr[16]}]
set_property src_info {type:XDC file:9 line:426 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_destination_addr[17]}]
set_property src_info {type:XDC file:9 line:427 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_destination_addr[18]}]
set_property src_info {type:XDC file:9 line:428 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_destination_addr[19]}]
set_property src_info {type:XDC file:9 line:429 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_destination_addr[1]}]
set_property src_info {type:XDC file:9 line:430 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_destination_addr[20]}]
set_property src_info {type:XDC file:9 line:431 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_destination_addr[21]}]
set_property src_info {type:XDC file:9 line:432 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_destination_addr[22]}]
set_property src_info {type:XDC file:9 line:433 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_destination_addr[23]}]
set_property src_info {type:XDC file:9 line:434 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_destination_addr[24]}]
set_property src_info {type:XDC file:9 line:435 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_destination_addr[25]}]
set_property src_info {type:XDC file:9 line:436 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_destination_addr[26]}]
set_property src_info {type:XDC file:9 line:437 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_destination_addr[27]}]
set_property src_info {type:XDC file:9 line:438 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_destination_addr[28]}]
set_property src_info {type:XDC file:9 line:439 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_destination_addr[29]}]
set_property src_info {type:XDC file:9 line:440 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_destination_addr[2]}]
set_property src_info {type:XDC file:9 line:441 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_destination_addr[30]}]
set_property src_info {type:XDC file:9 line:442 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_destination_addr[31]}]
set_property src_info {type:XDC file:9 line:443 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_destination_addr[3]}]
set_property src_info {type:XDC file:9 line:444 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_destination_addr[4]}]
set_property src_info {type:XDC file:9 line:445 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_destination_addr[5]}]
set_property src_info {type:XDC file:9 line:446 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_destination_addr[6]}]
set_property src_info {type:XDC file:9 line:447 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_destination_addr[7]}]
set_property src_info {type:XDC file:9 line:448 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_destination_addr[8]}]
set_property src_info {type:XDC file:9 line:449 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {ip_rec_destination_addr[9]}]
set_property src_info {type:XDC file:9 line:450 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_rec_destination_port[0]}]
set_property src_info {type:XDC file:9 line:451 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_rec_destination_port[10]}]
set_property src_info {type:XDC file:9 line:452 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_rec_destination_port[11]}]
set_property src_info {type:XDC file:9 line:453 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_rec_destination_port[12]}]
set_property src_info {type:XDC file:9 line:454 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_rec_destination_port[13]}]
set_property src_info {type:XDC file:9 line:455 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_rec_destination_port[14]}]
set_property src_info {type:XDC file:9 line:456 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_rec_destination_port[15]}]
set_property src_info {type:XDC file:9 line:457 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_rec_destination_port[1]}]
set_property src_info {type:XDC file:9 line:458 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_rec_destination_port[2]}]
set_property src_info {type:XDC file:9 line:459 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_rec_destination_port[3]}]
set_property src_info {type:XDC file:9 line:460 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_rec_destination_port[4]}]
set_property src_info {type:XDC file:9 line:461 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_rec_destination_port[5]}]
set_property src_info {type:XDC file:9 line:462 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_rec_destination_port[6]}]
set_property src_info {type:XDC file:9 line:463 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_rec_destination_port[7]}]
set_property src_info {type:XDC file:9 line:464 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_rec_destination_port[8]}]
set_property src_info {type:XDC file:9 line:465 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_rec_destination_port[9]}]
set_property src_info {type:XDC file:9 line:466 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_rec_source_port[0]}]
set_property src_info {type:XDC file:9 line:467 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_rec_source_port[10]}]
set_property src_info {type:XDC file:9 line:468 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_rec_source_port[11]}]
set_property src_info {type:XDC file:9 line:469 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_rec_source_port[12]}]
set_property src_info {type:XDC file:9 line:470 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_rec_source_port[13]}]
set_property src_info {type:XDC file:9 line:471 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_rec_source_port[14]}]
set_property src_info {type:XDC file:9 line:472 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_rec_source_port[15]}]
set_property src_info {type:XDC file:9 line:473 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_rec_source_port[1]}]
set_property src_info {type:XDC file:9 line:474 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_rec_source_port[2]}]
set_property src_info {type:XDC file:9 line:475 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_rec_source_port[3]}]
set_property src_info {type:XDC file:9 line:476 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_rec_source_port[4]}]
set_property src_info {type:XDC file:9 line:477 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_rec_source_port[5]}]
set_property src_info {type:XDC file:9 line:478 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_rec_source_port[6]}]
set_property src_info {type:XDC file:9 line:479 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_rec_source_port[7]}]
set_property src_info {type:XDC file:9 line:480 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_rec_source_port[8]}]
set_property src_info {type:XDC file:9 line:481 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_rec_source_port[9]}]
set_property src_info {type:XDC file:9 line:482 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_data_length[0]}]
set_property src_info {type:XDC file:9 line:483 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_data_length[10]}]
set_property src_info {type:XDC file:9 line:484 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_data_length[11]}]
set_property src_info {type:XDC file:9 line:485 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_data_length[12]}]
set_property src_info {type:XDC file:9 line:486 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_data_length[13]}]
set_property src_info {type:XDC file:9 line:487 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_data_length[14]}]
set_property src_info {type:XDC file:9 line:488 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_data_length[15]}]
set_property src_info {type:XDC file:9 line:489 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_data_length[1]}]
set_property src_info {type:XDC file:9 line:490 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_data_length[2]}]
set_property src_info {type:XDC file:9 line:491 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_data_length[3]}]
set_property src_info {type:XDC file:9 line:492 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_data_length[4]}]
set_property src_info {type:XDC file:9 line:493 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_data_length[5]}]
set_property src_info {type:XDC file:9 line:494 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_data_length[6]}]
set_property src_info {type:XDC file:9 line:495 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_data_length[7]}]
set_property src_info {type:XDC file:9 line:496 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_data_length[8]}]
set_property src_info {type:XDC file:9 line:497 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {udp_data_length[9]}]
set_property src_info {type:XDC file:9 line:508 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_miss_cnt[0]}]
set_property src_info {type:XDC file:9 line:509 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_miss_cnt[10]}]
set_property src_info {type:XDC file:9 line:510 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_miss_cnt[11]}]
set_property src_info {type:XDC file:9 line:511 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_miss_cnt[12]}]
set_property src_info {type:XDC file:9 line:512 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_miss_cnt[13]}]
set_property src_info {type:XDC file:9 line:513 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_miss_cnt[14]}]
set_property src_info {type:XDC file:9 line:514 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_miss_cnt[15]}]
set_property src_info {type:XDC file:9 line:515 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_miss_cnt[16]}]
set_property src_info {type:XDC file:9 line:516 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_miss_cnt[17]}]
set_property src_info {type:XDC file:9 line:517 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_miss_cnt[18]}]
set_property src_info {type:XDC file:9 line:518 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_miss_cnt[19]}]
set_property src_info {type:XDC file:9 line:519 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_miss_cnt[1]}]
set_property src_info {type:XDC file:9 line:520 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_miss_cnt[20]}]
set_property src_info {type:XDC file:9 line:521 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_miss_cnt[21]}]
set_property src_info {type:XDC file:9 line:522 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_miss_cnt[22]}]
set_property src_info {type:XDC file:9 line:523 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_miss_cnt[23]}]
set_property src_info {type:XDC file:9 line:524 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_miss_cnt[24]}]
set_property src_info {type:XDC file:9 line:525 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_miss_cnt[25]}]
set_property src_info {type:XDC file:9 line:526 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_miss_cnt[26]}]
set_property src_info {type:XDC file:9 line:527 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_miss_cnt[27]}]
set_property src_info {type:XDC file:9 line:528 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_miss_cnt[28]}]
set_property src_info {type:XDC file:9 line:529 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_miss_cnt[29]}]
set_property src_info {type:XDC file:9 line:530 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_miss_cnt[2]}]
set_property src_info {type:XDC file:9 line:531 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_miss_cnt[30]}]
set_property src_info {type:XDC file:9 line:532 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_miss_cnt[31]}]
set_property src_info {type:XDC file:9 line:533 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_miss_cnt[3]}]
set_property src_info {type:XDC file:9 line:534 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_miss_cnt[4]}]
set_property src_info {type:XDC file:9 line:535 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_miss_cnt[5]}]
set_property src_info {type:XDC file:9 line:536 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_miss_cnt[6]}]
set_property src_info {type:XDC file:9 line:537 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_miss_cnt[7]}]
set_property src_info {type:XDC file:9 line:538 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_miss_cnt[8]}]
set_property src_info {type:XDC file:9 line:539 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_miss_cnt[9]}]
set_property src_info {type:XDC file:9 line:540 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_trans_time[0]}]
set_property src_info {type:XDC file:9 line:541 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_trans_time[10]}]
set_property src_info {type:XDC file:9 line:542 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_trans_time[11]}]
set_property src_info {type:XDC file:9 line:543 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_trans_time[12]}]
set_property src_info {type:XDC file:9 line:544 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_trans_time[13]}]
set_property src_info {type:XDC file:9 line:545 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_trans_time[14]}]
set_property src_info {type:XDC file:9 line:546 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_trans_time[15]}]
set_property src_info {type:XDC file:9 line:547 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_trans_time[16]}]
set_property src_info {type:XDC file:9 line:548 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_trans_time[17]}]
set_property src_info {type:XDC file:9 line:549 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_trans_time[18]}]
set_property src_info {type:XDC file:9 line:550 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_trans_time[19]}]
set_property src_info {type:XDC file:9 line:551 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_trans_time[1]}]
set_property src_info {type:XDC file:9 line:552 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_trans_time[20]}]
set_property src_info {type:XDC file:9 line:553 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_trans_time[21]}]
set_property src_info {type:XDC file:9 line:554 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_trans_time[22]}]
set_property src_info {type:XDC file:9 line:555 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_trans_time[23]}]
set_property src_info {type:XDC file:9 line:556 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_trans_time[24]}]
set_property src_info {type:XDC file:9 line:557 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_trans_time[25]}]
set_property src_info {type:XDC file:9 line:558 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_trans_time[26]}]
set_property src_info {type:XDC file:9 line:559 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_trans_time[27]}]
set_property src_info {type:XDC file:9 line:560 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_trans_time[28]}]
set_property src_info {type:XDC file:9 line:561 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_trans_time[29]}]
set_property src_info {type:XDC file:9 line:562 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_trans_time[2]}]
set_property src_info {type:XDC file:9 line:563 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_trans_time[30]}]
set_property src_info {type:XDC file:9 line:564 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_trans_time[31]}]
set_property src_info {type:XDC file:9 line:565 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_trans_time[3]}]
set_property src_info {type:XDC file:9 line:566 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_trans_time[4]}]
set_property src_info {type:XDC file:9 line:567 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_trans_time[5]}]
set_property src_info {type:XDC file:9 line:568 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_trans_time[6]}]
set_property src_info {type:XDC file:9 line:569 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_trans_time[7]}]
set_property src_info {type:XDC file:9 line:570 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_trans_time[8]}]
set_property src_info {type:XDC file:9 line:571 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_trans_time[9]}]
set_property src_info {type:XDC file:9 line:572 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_data_length[0]}]
set_property src_info {type:XDC file:9 line:573 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_data_length[10]}]
set_property src_info {type:XDC file:9 line:574 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_data_length[11]}]
set_property src_info {type:XDC file:9 line:575 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_data_length[12]}]
set_property src_info {type:XDC file:9 line:576 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_data_length[13]}]
set_property src_info {type:XDC file:9 line:577 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_data_length[14]}]
set_property src_info {type:XDC file:9 line:578 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_data_length[15]}]
set_property src_info {type:XDC file:9 line:579 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_data_length[16]}]
set_property src_info {type:XDC file:9 line:580 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_data_length[17]}]
set_property src_info {type:XDC file:9 line:581 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_data_length[18]}]
set_property src_info {type:XDC file:9 line:582 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_data_length[19]}]
set_property src_info {type:XDC file:9 line:583 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_data_length[1]}]
set_property src_info {type:XDC file:9 line:584 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_data_length[20]}]
set_property src_info {type:XDC file:9 line:585 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_data_length[21]}]
set_property src_info {type:XDC file:9 line:586 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_data_length[22]}]
set_property src_info {type:XDC file:9 line:587 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_data_length[23]}]
set_property src_info {type:XDC file:9 line:588 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_data_length[24]}]
set_property src_info {type:XDC file:9 line:589 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_data_length[25]}]
set_property src_info {type:XDC file:9 line:590 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_data_length[26]}]
set_property src_info {type:XDC file:9 line:591 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_data_length[27]}]
set_property src_info {type:XDC file:9 line:592 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_data_length[28]}]
set_property src_info {type:XDC file:9 line:593 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_data_length[29]}]
set_property src_info {type:XDC file:9 line:594 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_data_length[2]}]
set_property src_info {type:XDC file:9 line:595 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_data_length[30]}]
set_property src_info {type:XDC file:9 line:596 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_data_length[31]}]
set_property src_info {type:XDC file:9 line:597 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_data_length[3]}]
set_property src_info {type:XDC file:9 line:598 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_data_length[4]}]
set_property src_info {type:XDC file:9 line:599 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_data_length[5]}]
set_property src_info {type:XDC file:9 line:600 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_data_length[6]}]
set_property src_info {type:XDC file:9 line:601 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_data_length[7]}]
set_property src_info {type:XDC file:9 line:602 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_data_length[8]}]
set_property src_info {type:XDC file:9 line:603 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {throughput_data_length[9]}]
set_property src_info {type:XDC file:9 line:605 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {states_ram/flow_cnt_reg[0]}]
set_property src_info {type:XDC file:9 line:606 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {states_ram/flow_cnt_reg[10]}]
set_property src_info {type:XDC file:9 line:607 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {states_ram/flow_cnt_reg[11]}]
set_property src_info {type:XDC file:9 line:608 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {states_ram/flow_cnt_reg[12]}]
set_property src_info {type:XDC file:9 line:609 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {states_ram/flow_cnt_reg[13]}]
set_property src_info {type:XDC file:9 line:610 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {states_ram/flow_cnt_reg[14]}]
set_property src_info {type:XDC file:9 line:611 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {states_ram/flow_cnt_reg[15]}]
set_property src_info {type:XDC file:9 line:612 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {states_ram/flow_cnt_reg[1]}]
set_property src_info {type:XDC file:9 line:613 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {states_ram/flow_cnt_reg[2]}]
set_property src_info {type:XDC file:9 line:614 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {states_ram/flow_cnt_reg[3]}]
set_property src_info {type:XDC file:9 line:615 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {states_ram/flow_cnt_reg[4]}]
set_property src_info {type:XDC file:9 line:616 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {states_ram/flow_cnt_reg[5]}]
set_property src_info {type:XDC file:9 line:617 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {states_ram/flow_cnt_reg[6]}]
set_property src_info {type:XDC file:9 line:618 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {states_ram/flow_cnt_reg[7]}]
set_property src_info {type:XDC file:9 line:619 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {states_ram/flow_cnt_reg[8]}]
set_property src_info {type:XDC file:9 line:620 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {states_ram/flow_cnt_reg[9]}]
set_property src_info {type:XDC file:9 line:621 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets u_ila_1_gmii_rx_clk]
set_property src_info {type:XDC file:9 line:623 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_gmii_rx_clk]
set_property src_info {type:XDC file:9 line:634 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_test/u2/mac_test0/mac_top0/mac_rx0/udp0/rx_cnt_reg[13]}]
set_property src_info {type:XDC file:9 line:635 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_test/u2/mac_test0/mac_top0/mac_rx0/udp0/rx_cnt_reg[11]}]
set_property src_info {type:XDC file:9 line:636 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_test/u2/mac_test0/mac_top0/mac_rx0/udp0/rx_cnt_reg[6]}]
set_property src_info {type:XDC file:9 line:637 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_test/u2/mac_test0/mac_top0/mac_rx0/udp0/rx_cnt_reg[2]}]
set_property src_info {type:XDC file:9 line:638 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_test/u2/mac_test0/mac_top0/mac_rx0/udp0/rx_cnt_reg[5]}]
set_property src_info {type:XDC file:9 line:639 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_test/u2/mac_test0/mac_top0/mac_rx0/udp0/rx_cnt_reg[4]}]
set_property src_info {type:XDC file:9 line:640 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_test/u2/mac_test0/mac_top0/mac_rx0/udp0/rx_cnt_reg[12]}]
set_property src_info {type:XDC file:9 line:641 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_test/u2/mac_test0/mac_top0/mac_rx0/udp0/rx_cnt_reg[10]}]
set_property src_info {type:XDC file:9 line:642 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_test/u2/mac_test0/mac_top0/mac_rx0/udp0/rx_cnt_reg[14]}]
set_property src_info {type:XDC file:9 line:643 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_test/u2/mac_test0/mac_top0/mac_rx0/udp0/rx_cnt_reg[7]}]
set_property src_info {type:XDC file:9 line:644 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_test/u2/mac_test0/mac_top0/mac_rx0/udp0/rx_cnt_reg[9]}]
set_property src_info {type:XDC file:9 line:645 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_test/u2/mac_test0/mac_top0/mac_rx0/udp0/rx_cnt_reg[15]}]
set_property src_info {type:XDC file:9 line:646 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_test/u2/mac_test0/mac_top0/mac_rx0/udp0/rx_cnt_reg[3]}]
set_property src_info {type:XDC file:9 line:647 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_test/u2/mac_test0/mac_top0/mac_rx0/udp0/rx_cnt_reg[8]}]
set_property src_info {type:XDC file:9 line:648 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {states_ram/flow_cnt_reg[0]} {states_ram/flow_cnt_reg[1]} {states_ram/flow_cnt_reg[2]} {states_ram/flow_cnt_reg[3]} {states_ram/flow_cnt_reg[4]} {states_ram/flow_cnt_reg[5]} {states_ram/flow_cnt_reg[6]} {states_ram/flow_cnt_reg[7]} {states_ram/flow_cnt_reg[8]} {states_ram/flow_cnt_reg[9]} {states_ram/flow_cnt_reg[10]} {states_ram/flow_cnt_reg[11]} {states_ram/flow_cnt_reg[12]} {states_ram/flow_cnt_reg[13]} {states_ram/flow_cnt_reg[14]} {states_ram/flow_cnt_reg[15]}]]
set_property src_info {type:XDC file:9 line:649 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe0 [get_nets [list {eth_test/u2/mac_test0/mac_top0/mac_rx0/udp0/rx_cnt_reg[2]} {eth_test/u2/mac_test0/mac_top0/mac_rx0/udp0/rx_cnt_reg[3]} {eth_test/u2/mac_test0/mac_top0/mac_rx0/udp0/rx_cnt_reg[4]} {eth_test/u2/mac_test0/mac_top0/mac_rx0/udp0/rx_cnt_reg[5]} {eth_test/u2/mac_test0/mac_top0/mac_rx0/udp0/rx_cnt_reg[6]} {eth_test/u2/mac_test0/mac_top0/mac_rx0/udp0/rx_cnt_reg[7]} {eth_test/u2/mac_test0/mac_top0/mac_rx0/udp0/rx_cnt_reg[8]} {eth_test/u2/mac_test0/mac_top0/mac_rx0/udp0/rx_cnt_reg[9]} {eth_test/u2/mac_test0/mac_top0/mac_rx0/udp0/rx_cnt_reg[10]} {eth_test/u2/mac_test0/mac_top0/mac_rx0/udp0/rx_cnt_reg[11]} {eth_test/u2/mac_test0/mac_top0/mac_rx0/udp0/rx_cnt_reg[12]} {eth_test/u2/mac_test0/mac_top0/mac_rx0/udp0/rx_cnt_reg[13]} {eth_test/u2/mac_test0/mac_top0/mac_rx0/udp0/rx_cnt_reg[14]} {eth_test/u2/mac_test0/mac_top0/mac_rx0/udp0/rx_cnt_reg[15]}]]
set_property src_info {type:XDC file:9 line:651 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:9 line:652 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:9 line:653 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:9 line:654 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:9 line:655 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:9 line:656 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:9 line:657 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:9 line:658 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:9 line:659 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:9 line:660 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:9 line:661 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list eth_test/u1/util_gmii_to_rgmii_m0/gmii_rx_clk]]
set_property src_info {type:XDC file:9 line:662 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:9 line:663 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:9 line:664 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {throughput_trans_time[0]} {throughput_trans_time[1]} {throughput_trans_time[2]} {throughput_trans_time[3]} {throughput_trans_time[4]} {throughput_trans_time[5]} {throughput_trans_time[6]} {throughput_trans_time[7]} {throughput_trans_time[8]} {throughput_trans_time[9]} {throughput_trans_time[10]} {throughput_trans_time[11]} {throughput_trans_time[12]} {throughput_trans_time[13]} {throughput_trans_time[14]} {throughput_trans_time[15]} {throughput_trans_time[16]} {throughput_trans_time[17]} {throughput_trans_time[18]} {throughput_trans_time[19]} {throughput_trans_time[20]} {throughput_trans_time[21]} {throughput_trans_time[22]} {throughput_trans_time[23]} {throughput_trans_time[24]} {throughput_trans_time[25]} {throughput_trans_time[26]} {throughput_trans_time[27]} {throughput_trans_time[28]} {throughput_trans_time[29]} {throughput_trans_time[30]} {throughput_trans_time[31]}]]
set_property src_info {type:XDC file:9 line:665 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:9 line:666 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:9 line:667 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:9 line:668 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {throughput_data_length[0]} {throughput_data_length[1]} {throughput_data_length[2]} {throughput_data_length[3]} {throughput_data_length[4]} {throughput_data_length[5]} {throughput_data_length[6]} {throughput_data_length[7]} {throughput_data_length[8]} {throughput_data_length[9]} {throughput_data_length[10]} {throughput_data_length[11]} {throughput_data_length[12]} {throughput_data_length[13]} {throughput_data_length[14]} {throughput_data_length[15]} {throughput_data_length[16]} {throughput_data_length[17]} {throughput_data_length[18]} {throughput_data_length[19]} {throughput_data_length[20]} {throughput_data_length[21]} {throughput_data_length[22]} {throughput_data_length[23]} {throughput_data_length[24]} {throughput_data_length[25]} {throughput_data_length[26]} {throughput_data_length[27]} {throughput_data_length[28]} {throughput_data_length[29]} {throughput_data_length[30]} {throughput_data_length[31]}]]
set_property src_info {type:XDC file:9 line:669 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:9 line:670 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:9 line:671 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:9 line:672 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {throughput_miss_cnt[0]} {throughput_miss_cnt[1]} {throughput_miss_cnt[2]} {throughput_miss_cnt[3]} {throughput_miss_cnt[4]} {throughput_miss_cnt[5]} {throughput_miss_cnt[6]} {throughput_miss_cnt[7]} {throughput_miss_cnt[8]} {throughput_miss_cnt[9]} {throughput_miss_cnt[10]} {throughput_miss_cnt[11]} {throughput_miss_cnt[12]} {throughput_miss_cnt[13]} {throughput_miss_cnt[14]} {throughput_miss_cnt[15]} {throughput_miss_cnt[16]} {throughput_miss_cnt[17]} {throughput_miss_cnt[18]} {throughput_miss_cnt[19]} {throughput_miss_cnt[20]} {throughput_miss_cnt[21]} {throughput_miss_cnt[22]} {throughput_miss_cnt[23]} {throughput_miss_cnt[24]} {throughput_miss_cnt[25]} {throughput_miss_cnt[26]} {throughput_miss_cnt[27]} {throughput_miss_cnt[28]} {throughput_miss_cnt[29]} {throughput_miss_cnt[30]} {throughput_miss_cnt[31]}]]
set_property src_info {type:XDC file:9 line:673 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:9 line:674 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:9 line:675 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:9 line:676 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets gmii_tx_clk_out]
set_property src_info {type:SCOPED_XDC file:10 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_clocks -of_objects [get_pins eth_test/u1/ten_gig_eth_example_top/inst_ten_gig_mac_wrapper/ten_gig_eth_pcs_pma_i/inst/txusrclk2]] -to [get_pins -of_objects [get_cells -hier -filter {NAME =~ *coreclk_rxusrclk2_timer_125us_resync/*synchc_inst*d1_reg}] -filter {NAME =~ *D}] 6.400
set_property src_info {type:SCOPED_XDC file:10 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_clocks -of_objects [get_pins eth_test/u1/ten_gig_eth_example_top/inst_ten_gig_mac_wrapper/ten_gig_eth_pcs_pma_i/inst/txusrclk2]] -to [get_pins -of_objects [get_cells -hierarchical -filter {NAME =~ *drp_ipif_i*synch_*q_reg*}] -filter {NAME =~ *D || NAME =~ *R || NAME =~ *S}] 3.100
set_property src_info {type:SCOPED_XDC file:11 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_clocks -of_objects [get_pins eth_test/u2/ten_gig_eth_example_top/inst_ten_gig_mac_wrapper/ten_gig_eth_pcs_pma_i/inst/txusrclk2]] -to [get_pins -of_objects [get_cells -hier -filter {NAME =~ *coreclk_rxusrclk2_timer_125us_resync/*synchc_inst*d1_reg}] -filter {NAME =~ *D}] 6.400
set_property src_info {type:SCOPED_XDC file:11 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_clocks -of_objects [get_pins eth_test/u2/ten_gig_eth_example_top/inst_ten_gig_mac_wrapper/ten_gig_eth_pcs_pma_i/inst/txusrclk2]] -to [get_pins -of_objects [get_cells -hierarchical -filter {NAME =~ *drp_ipif_i*synch_*q_reg*}] -filter {NAME =~ *D || NAME =~ *R || NAME =~ *S}] 3.100
